sudo: false
language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
- npm install grunt-cli -g
cache:
  directories:
  - node_modules
  - bower_components
deploy:
  provider: heroku
  api_key:
    secure: 3z66A6WEgvnyWXkyVRDLHRKOJajkeVZxQZ4zXk+4o/P9E9dZ48tX+sCWsJpfDnrzwHa6/uC5/UGw6PvaS8a+aSL3Ze6G2yHOXoZ0AjAO8CEE+lxUG43vSQCQucoAahIp8zKq5xHeLxNsynLD5wHPVDCjXYgKnhIUhYX5Ak6BRb7yaHngQq7lf1vQ1e7Lg8ltx+hqWZ5oyqc8bkKLfbaxy9L9a7ZuR3O5miZnRWsrhYnvyl8W1ruQSrjsDIqlDKzSX9plYxBRrSXo9UQe3VSRNawZjGN9UlFzLFpTnI0agOLn4aUEHIJvOWPe6WNROWdn9n8CFXmi5rHZLtCXcO9ZsmgQkQPxWv4Fo4CyjX/UqPkrX1dQh9JDHpESp2qSbrDxlV8PKlJVCXYwtFB1dWOaWF/ik1vI6fQP2sIsJcowJ/3t0OWfxLlobg4EU0h0RI1ZMVYqQPiSYgpao9QYOlP6OIi1ig0nKfnH6OVA3Pbzjo5ZXsLIGLBmjvauucoRVCxd/l/JOU8MqbVc4uqj5jz433ippZ7CtrS3nu8NgD6JvsuZYR0VGCU9S3XBrZOW1oIVO21dY4uj1XjxogFyTw/G1lHj09ZFrgp6sfkqUnNgXcrhdkZqDXh7hk5evwtygKUWLIkd/z+xSQkp5apl1LdqIi/0Qb+ggEN1rZEAK9HzTlQ=
  app: stamplayinfoshre
  on:
    master
  run:
  - grunt build
  - node server.js
